In [2]:
import tensorflow as tf
import numpy as np
from scipy.spatial.distance import cdist

M1, M2, K = 3, 4, 2

# Scipy calculation
a = np.random.rand(M1, K).astype(np.float32)
b = np.random.rand(M2, K).astype(np.float32)
print(cdist(a, b, 'euclidean'), '\n')

# TF calculation
A = tf.Variable(a)
B = tf.Variable(b)

p1 = tf.matmul(
    tf.expand_dims(tf.reduce_sum(tf.square(A), 1), 1),
    tf.ones(shape=(1, M2))
)
p2 = tf.transpose(tf.matmul(
    tf.reshape(tf.reduce_sum(tf.square(B), 1), shape=[-1, 1]),
    tf.ones(shape=(M1, 1)),
    transpose_b=True
))

res = tf.sqrt(tf.add(p1, p2) - 2 * tf.matmul(A, B, transpose_b=True))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(res))

[[ 0.80034184  0.34679877  0.82221301  0.14916446]
 [ 0.62041231  0.34149322  0.28771224  0.62199262]
 [ 0.46967778  0.46299796  0.24106646  0.62617749]] 

[[ 0.80034202  0.34679875  0.82221305  0.14916451]
 [ 0.62041235  0.34149313  0.28771213  0.62199265]
 [ 0.46967781  0.46299791  0.24106634  0.62617737]]
